### ISSUE TITLE
minLevel not being set on le_node

### ISSUE THREAD

**Issue by chazmo03** [nemtsov/node-bunyan-logentries#4]
I'm seeing an issue I haven't seen before after almost a year of using this package. It looks like le_node is filtering out debug and trace messages and there's no place on the API to configure this. When using bunyan, I think the expected usage would be to configure the min level in bunyan and then have le_node just pipe everything through. This is using 0.2.1 of le_node, which seems to set minLevel to 1 instead of 0. I hacked in `logentriesStream._logger.level('trace');` to work around this, but should this library update to a newer version of le_node?

**Comment by nemtsov** [comment]
Sure. Are you interested in doing a PR?

**Comment by chazmo03** [comment]
Sure, I'll try to pull it together in the next few days. To just upgrade to the latest le_node? Do you happen to know where version 0.2.1 of le_node came from?

**Comment by nemtsov** [comment]
Let's start with the version. But please propose more changes if needed. I
think that's the version that was available at the time I released this.

**Comment by chazmo03** [comment]
It looks like the newer version of le_node is designed (and documented) to be used quite easily directly with bunyan. I think that's the better option so I don't think there's much use for this module.
